receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:94317
      http:
        endpoint: 0.0.0.0:94318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  attributes:
    actions:
      - key: environment
        value: production
        action: upsert

importers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'opentelemetry'
          scrape_interval: 15s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  prometheus:
    endpoint: 0.0.0.0:8888
  otlp:
    endpoint: jaeger:94317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:9310/loki/api/v1/push

service:
  pipelines:
    traces:
      receivers: [otlp]]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki]