apiVersion: v1
kind: Secret
metadata:
  name: setup-service-secret
  namespace: setup
type: Opaque
stringData:
  db_username: "gindho"
  db_password: "gindho123"
  jwt_secret: "default-secret-change-me"
  keycloak_admin_username: "admin"
  keycloak_admin_password: "admin123"
  keycloak_client_secret: "test-secret"
