apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
  namespace: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:3.6
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yml"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:9041"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:9040"
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
          ports:
            - containerPort: 9040
              name: proxy
            - containerPort: 9041
              name: admin
          volumeMounts:
            - name: kong-config
              mountPath: /kong/declarative
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
      volumes:
        - name: kong-config
          configMap:
            name: kong-declarative-config