apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure
resources:
  - postgresql/statefulset.yaml
  - mongodb/statefulset.yaml
  - redis/statefulset.yaml
  - kafka/kafka-sts.yaml
  - kafka/zookeeper-sts.yaml
  - keycloak/statefulset.yaml
  - kong/deployment.yaml
  - prometheus/prometheus-operator.yaml
  - grafana/deployment.yaml
  - jaeger/deployment.yaml
  - loki/deployment.yaml
  - secrets.yaml
  - kafka-topics.yaml
configMapGenerator:
  - name: gindho-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - SPRING_PROFILES_ACTIVE=dev