# GinDHO — Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9990']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:9041']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'patient-service:9004'
          - 'appointment-service:9005'
          - 'medical-record-service:9006'
          - 'billing-service:9007'
          - 'identity-service:9008'
          - 'authorization-service:9009'
          - 'notification-service:9010'
          - 'reporting-service:9011'
          - 'inventory-service:9012'
          - 'pharmacy-service:9013'
          - 'laboratory-service:9014'
          - 'emergency-service:9015'

rule_files:
  - 'alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']