apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-addons
  namespace: monitoring
data:
  kiali.yaml: |
    apiVersion: kiali.io/v1alpha1
    kind: Kiali
    metadata:
      name: kiali
      namespace: istio-system
    spec:
      auth:
        strategy: anonymous
      deployment:
        accessible_namespaces: ["gindho"]
  jaeger.yaml: |
    apiVersion: jaegertracing.io/v1
    kind: Jaeger
    metadata:
      name: jaeger
      namespace: monitoring
    spec:
      strategy: production
      storage:
        type: elasticsearch
        options:
          es:
            serverUrl: http://elasticsearch.monitoring.svc.cluster.local:9200
      query:
        service_monitor: true
      collector:
        service_monitor: true
      sampling:
        default_strategy:
          type: probabilistic
          param: 100