global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9990']
  - job_name: spring-boot-apps
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - patient-service:9004
          - appointment-service:9005
          - billing-service:9007
