package com.gindho.config;

import org.springframework.cloud.gateway.route.RouteLocator;
import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder;
import org.springframework.cloud.gateway.filter.ratelimit.KeyResolver;
import org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import reactor.core.publisher.Mono;

@Configuration
public class GatewayConfig {

    @Bean
    public RouteLocator customRouteLocator(RouteLocatorBuilder builder) {
        return builder.routes()
                .route("identity-service", r -> r.path("/api/auth/**", "/api/users/**")
                        .filters(f -> f.rewritePath("/api/(?<segment>.*)", "/api/${segment}")
                                .circuitBreaker(c -> c.setName("identity-cb")
                                        .setFallbackUri("forward:/fallback/identity")))
                        .uri("lb://identity-service"))
                .route("authorization-service", r -> r.path("/api/authorization/**", "/api/admin/**")
                        .filters(f -> f.rewritePath("/api/(?<segment>.*)", "/api/${segment}")
                                .circuitBreaker(c -> c.setName("authz-cb")
                                        .setFallbackUri("forward:/fallback/authz")))
                        .uri("lb://authorization-service"))
                .route("patient-service", r -> r.path("/api/patients/**")
                        .filters(f -> f.rewritePath("/api/patients/(?<segment>.*)", "/api/patients/${segment}")
                                .circuitBreaker(c -> c.setName("patient-cb")
                                        .setFallbackUri("forward:/fallback/patient")))
                        .uri("lb://patient-service"))
                .route("appointment-service", r -> r.path("/api/appointments/**", "/api/availability/**")
                        .filters(f -> f.rewritePath("/api/appointments/(?<segment>.*)", "/api/appointments/${segment}")
                                .rewritePath("/api/availability/(?<segment>.*)", "/api/availability/${segment}")
                                .circuitBreaker(c -> c.setName("appointment-cb")
                                        .setFallbackUri("forward:/fallback/appointment")))
                        .uri("lb://appointment-service"))
                .route("medical-record-service", r -> r.path("/api/emr/**", "/api/medical-records/**")
                        .filters(f -> f.rewritePath("/api/emr/(?<segment>.*)", "/api/emr/${segment}")
                                .circuitBreaker(c -> c.setName("emr-cb")
                                        .setFallbackUri("forward:/fallback/emr")))
                        .uri("lb://medical-record-service"))
                .route("admission-service", r -> r.path("/api/admissions/**")
                        .filters(f -> f.rewritePath("/api/admissions/(?<segment>.*)", "/api/admissions/${segment}")
                                .circuitBreaker(c -> c.setName("admission-cb")
                                        .setFallbackUri("forward:/fallback/admission")))
                        .uri("lb://admission-service"))
                .route("emergency-service", r -> r.path("/api/emergency/**")
                        .filters(f -> f.rewritePath("/api/emergency/(?<segment>.*)", "/api/emergency/${segment}")
                                .circuitBreaker(c -> c.setName("emergency-cb")
                                        .setFallbackUri("forward:/fallback/emergency")))
                        .uri("lb://emergency-service"))
                .route("ward-service", r -> r.path("/api/wards/**")
                        .filters(f -> f.rewritePath("/api/wards/(?<segment>.*)", "/api/wards/${segment}")
                                .circuitBreaker(c -> c.setName("ward-cb")
                                        .setFallbackUri("forward:/fallback/ward")))
                        .uri("lb://ward-service"))
                .route("bed-service", r -> r.path("/api/beds/**")
                        .filters(f -> f.rewritePath("/api/beds/(?<segment>.*)", "/api/beds/${segment}")
                                .circuitBreaker(c -> c.setName("bed-cb")
                                        .setFallbackUri("forward:/fallback/bed")))
                        .uri("lb://bed-service"))
                .route("round-service", r -> r.path("/api/rounds/**")
                        .filters(f -> f.rewritePath("/api/rounds/(?<segment>.*)", "/api/rounds/${segment}")
                                .circuitBreaker(c -> c.setName("round-cb")
                                        .setFallbackUri("forward:/fallback/round")))
                        .uri("lb://round-service"))
                .route("surgery-service", r -> r.path("/api/surgeries/**")
                        .filters(f -> f.rewritePath("/api/surgeries/(?<segment>.*)", "/api/surgeries/${segment}")
                                .circuitBreaker(c -> c.setName("surgery-cb")
                                        .setFallbackUri("forward:/fallback/surgery")))
                        .uri("lb://surgery-service"))
                .route("prescription-service", r -> r.path("/api/prescriptions/**")
                        .filters(f -> f.rewritePath("/api/prescriptions/(?<segment>.*)", "/api/prescriptions/${segment}")
                                .circuitBreaker(c -> c.setName("prescription-cb")
                                        .setFallbackUri("forward:/fallback/prescription")))
                        .uri("lb://prescription-service"))
                .route("pharmacy-service", r -> r.path("/api/pharmacy/**")
                        .filters(f -> f.rewritePath("/api/pharmacy/(?<segment>.*)", "/api/pharmacy/${segment}")
                                .circuitBreaker(c -> c.setName("pharmacy-cb")
                                        .setFallbackUri("forward:/fallback/pharmacy")))
                        .uri("lb://pharmacy-service"))
                .route("laboratory-service", r -> r.path("/api/laboratory/**", "/api/lab/**")
                        .filters(f -> f.rewritePath("/api/laboratory/(?<segment>.*)", "/api/laboratory/${segment}")
                                .rewritePath("/api/lab/(?<segment>.*)", "/api/lab/${segment}")
                                .circuitBreaker(c -> c.setName("lab-cb")
                                        .setFallbackUri("forward:/fallback/lab")))
                        .uri("lb://laboratory-service"))
                .route("imaging-service", r -> r.path("/api/imaging/**")
                        .filters(f -> f.rewritePath("/api/imaging/(?<segment>.*)", "/api/imaging/${segment}")
                                .circuitBreaker(c -> c.setName("imaging-cb")
                                        .setFallbackUri("forward:/fallback/imaging")))
                        .uri("lb://imaging-service"))
                .route("billing-service", r -> r.path("/api/billing/**", "/api/invoices/**")
                        .filters(f -> f.rewritePath("/api/billing/(?<segment>.*)", "/api/billing/${segment}")
                                .rewritePath("/api/invoices/(?<segment>.*)", "/api/invoices/${segment}")
                                .circuitBreaker(c -> c.setName("billing-cb")
                                        .setFallbackUri("forward:/fallback/billing")))
                        .uri("lb://billing-service"))
                .route("insurance-service", r -> r.path("/api/insurance/**")
                        .filters(f -> f.rewritePath("/api/insurance/(?<segment>.*)", "/api/insurance/${segment}")
                                .circuitBreaker(c -> c.setName("insurance-cb")
                                        .setFallbackUri("forward:/fallback/insurance")))
                        .uri("lb://insurance-service"))
                .route("payment-service", r -> r.path("/api/payments/**")
                        .filters(f -> f.rewritePath("/api/payments/(?<segment>.*)", "/api/payments/${segment}")
                                .circuitBreaker(c -> c.setName("payment-cb")
                                        .setFallbackUri("forward:/fallback/payment")))
                        .uri("lb://payment-service"))
                .route("inventory-service", r -> r.path("/api/inventory/**")
                        .filters(f -> f.rewritePath("/api/inventory/(?<segment>.*)", "/api/inventory/${segment}")
                                .circuitBreaker(c -> c.setName("inventory-cb")
                                        .setFallbackUri("forward:/fallback/inventory")))
                        .uri("lb://inventory-service"))
                .route("procurement-service", r -> r.path("/api/procurement/**")
                        .filters(f -> f.rewritePath("/api/procurement/(?<segment>.*)", "/api/procurement/${segment}")
                                .circuitBreaker(c -> c.setName("procurement-cb")
                                        .setFallbackUri("forward:/fallback/procurement")))
                        .uri("lb://procurement-service"))
                .route("asset-service", r -> r.path("/api/assets/**")
                        .filters(f -> f.rewritePath("/api/assets/(?<segment>.*)", "/api/assets/${segment}")
                                .circuitBreaker(c -> c.setName("asset-cb")
                                        .setFallbackUri("forward:/fallback/asset")))
                        .uri("lb://asset-service"))
                .route("ambulance-service", r -> r.path("/api/ambulance/**")
                        .filters(f -> f.rewritePath("/api/ambulance/(?<segment>.*)", "/api/ambulance/${segment}")
                                .circuitBreaker(c -> c.setName("ambulance-cb")
                                        .setFallbackUri("forward:/fallback/ambulance")))
                        .uri("lb://ambulance-service"))
                .route("hr-service", r -> r.path("/api/hr/**")
                        .filters(f -> f.rewritePath("/api/hr/(?<segment>.*)", "/api/hr/${segment}")
                                .circuitBreaker(c -> c.setName("hr-cb")
                                        .setFallbackUri("forward:/fallback/hr")))
                        .uri("lb://hr-service"))
                .route("scheduling-service", r -> r.path("/api/schedules/**")
                        .filters(f -> f.rewritePath("/api/schedules/(?<segment>.*)", "/api/schedules/${segment}")
                                .circuitBreaker(c -> c.setName("scheduling-cb")
                                        .setFallbackUri("forward:/fallback/scheduling")))
                        .uri("lb://scheduling-service"))
                .route("event-service", r -> r.path("/api/events/**")
                        .filters(f -> f.rewritePath("/api/events/(?<segment>.*)", "/api/events/${segment}")
                                .circuitBreaker(c -> c.setName("event-cb")
                                        .setFallbackUri("forward:/fallback/event")))
                        .uri("lb://event-service"))
                .route("notification-service", r -> r.path("/api/notifications/**")
                        .filters(f -> f.rewritePath("/api/notifications/(?<segment>.*)", "/api/notifications/${segment}")
                                .circuitBreaker(c -> c.setName("notification-cb")
                                        .setFallbackUri("forward:/fallback/notification")))
                        .uri("lb://notification-service"))
                .route("reporting-service", r -> r.path("/api/reports/**", "/api/reporting/**")
                        .filters(f -> f.rewritePath("/api/reports/(?<segment>.*)", "/api/reports/${segment}")
                                .rewritePath("/api/reporting/(?<segment>.*)", "/api/reporting/${segment}")
                                .circuitBreaker(c -> c.setName("reporting-cb")
                                        .setFallbackUri("forward:/fallback/reporting")))
                        .uri("lb://reporting-service"))
                .route("audit-service", r -> r.path("/api/audit/**")
                        .filters(f -> f.rewritePath("/api/audit/(?<segment>.*)", "/api/audit/${segment}")
                                .circuitBreaker(c -> c.setName("audit-cb")
                                        .setFallbackUri("forward:/fallback/audit")))
                        .uri("lb://audit-service"))
                .route("legacy-monolith", r -> r.path("/api/legacy/**")
                        .filters(f -> {
                            var spec = f.rewritePath("/api/legacy/(?<segment>.*)", "/api/${segment}");
                            return spec.addRequestHeader("X-Gateway-Source", "spring-gateway");
                        })
                        .uri("lb://backend-service"))
                .build();
    }

    @Bean
    public KeyResolver userKeyResolver() {
        return exchange -> Mono.just("global");
    }
}
